name: Fuzz Testing CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fuzz-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the fuzz tests
      - name: Run Fuzz Tests
        run: python fuzz.py

      # Step 5: Display the contents of the fuzz report
      - name: Display Fuzz Report
        if: always()  # Always run to display logs even on failure
        run: cat fuzz_report.csv

      # Step 6: Upload the fuzz report as an artifact
      - name: Upload Fuzz Report
        if: always()  # Always upload the report even if the tests fail
        uses: actions/upload-artifact@v3
        with:
          name: fuzz-report
          path: fuzz_report.csv

      # Step 7: Save logs for debugging (optional)
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs/
