name: Fuzz Testing CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fuzz-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [[ -f requirements.txt && -s requirements.txt ]]; then
            pip install -r requirements.txt
          else
            echo "No dependencies to install (requirements.txt is missing or empty)."
          fi

      # Step 4: Run Fuzz Tests
      - name: Run Fuzz Tests
        run: |
          if [[ -f fuzz.py ]]; then
            python fuzz.py
          else
            echo "fuzz.py not found, cannot run tests."
            exit 1
          fi

      # Step 5: Display Fuzz Report
      - name: Display Fuzz Report
        if: always()
        run: |
          if [[ -f fuzz_report.csv ]]; then
            echo "Fuzz Report Found:"
            cat fuzz_report.csv
          else
            echo "No fuzz_report.csv found, no bugs reported."
          fi

      # Step 6: Upload the fuzz report as an artifact
      - name: Upload Fuzz Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: fuzz-report
          path: fuzz_report.csv

      # Step 7: Upload Logs
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: fuzz-logs
          path: fuzz_forensics.log
